version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: uni_registro
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: uni_registro
    tty: true

volumes:
  db_data:
